coverage:
  range: 85..100
  round: down
  precision: 1
  status:
    project:
      default:
        target: 100%
        threshold: 0%

ignore:
  - "tests"

comment:
  layout: "files"
  require_changes: yes
